### ISSUE TITLE
Works inside react for example? How it would be?

### ISSUE THREAD

**Issue by djalmaaraujo** [EdernClemente/TypeLighterJS-Typewriter#1]

**Comment by giocodes** [comment]
@djalmaaraujo here's a quick React implementation with Hooks
https://codesandbox.io/embed/typelighter-example-i4jrt

Notice that I had to fork and make the class and method exportables to use them after the markup was already rendered. 

@EdernClemente nice work here! Have you consider publishing it as an npm package?

**Comment by djalmaaraujo** [comment]
Nice. Thanks @giocodes =)

**Comment by EdernClemente** [comment]
Hello.  Thanks for your answer @giocodes. 👍 
I published the project as an npm package yesterday, and also created a CDN version.
Have a nice day =)

**Comment by giocodes** [comment]
Happy to help! 
Awesome, I tried the npm install and added some comments over here https://github.com/EdernClemente/TypeLighterJS/issues/2

Hope it helps!
