### ISSUE TITLE
HTML Entity handling

### ISSUE THREAD

**Issue by tomlutzenberger** [EdernClemente/TypeLighterJS-Typewriter#3]
Hi Edern.
I wanted to ask if there are plans to extend the functionality of TypeLighter. In a current project, I used your library and it works great.
But it turned out that it can't handle HTML entities or more specific "Soft-Hyphens" `&shy;`.
Because TypeLighter prints character after character, those entities get printed as well and show up as plain text until they're complete. I looked at your implementation and have some sort of idea how to solve this. Would you include such functionality?

**Comment by tomlutzenberger** [comment]
I found out that I can avoid/solve this problem by using escaped unicode characters. In my case using `\u00ad` instead of `&shy;` fixed everything.

**Comment by EdernClemente** [comment]
Hi @tomlutzenberger. Sorry for the delayed response, I’m working a lot this year. Thanks for your solution 🙂
